# Generated by Django 4.2.4 on 2023-08-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
