# Generated by Django 4.2.4 on 2023-08-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_topic_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='ordinal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
